apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: 'true'
  name: in-cluster
spec:
  destination:
    namespace: codefresh-hosted
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: >-
        {all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/codefresh-hosted/*.yaml,runtimes/codefresh-hosted/**/*.yaml,control-planes/*.yaml,control-planes/**/*.yaml,codefresh-hosted/default-git-source.yaml,codefresh-hosted/arn-aws-eks-us-east-1-336151728602-cluster-dan-csdp-rollouts.yaml,codefresh-hosted/arn-aws-eks-us-east-1-336151728602-cluster-dan-csdp-rollout-reporter.yaml}
      recurse: true
    path: shared-config/resources
    repoURL: https://github.com/danamzulescu-codefresh/eks-runtime.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
