apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: argo-events
  newName: quay.io/argo-proj/argo-events
  newTag: v1.6.3
kind: Kustomization
resources:
- github.com/codefresh-io/cli-v2/manifests/argo-events?ref=v0.0.412
