apiVersion: kustomize.config.k8s.io/v1beta1
configMapGenerator:
- behavior: merge
  literals:
  - argoWorkflowsInsecure=true
  - cfHost=https://g.codefresh.io
  - cors=https://g.codefresh.io
  - env=production
  - graphqlDebug=true
  - graphqlPlayground=true
  name: cap-app-proxy-cm
kind: Kustomization
namespace: dan-a-eks
resources:
- ../../base
- ingress.yaml

images:
  - name: quay.io/codefresh/cap-app-proxy
    newName: quay.io/noam_codefresh/cap-app-proxy
    newTag: dan
